### DISCUSSION TITLE
Campaign manager design Discussion

### DISCUSSION THREAD

**Discussion by iparask** [simonsobs/so_campaign_manager#35] [Ideas]
The campaign manager defines 3 campaign abstractions:

- Campaign: A campaign is a bag of workflows that we need to run. In addition to the workflows that are part of the campaign a campaign has attributes such as deadline, target resources. A definition of deadline is the maximum amount of the campaign is allowed to run. Target resource is the HPC that it will run. In our case, this can default to Tiger or Perlmutter.
  - There might be a reason to also define a policy. That could be minimize execution time, while maximizing the amount of resources, or minimize the amount of resources while achieving the deadline.

- Workflow: This is the basic workflow that one wants to execute as part of a campaign. These are static in terms of the SO related command they execute, for example `so-site-pipeline make-ml-maps` or `toast_so_sim`. Its configuration can be varied in terms of the scientific requirements. In addition, it can define the default number of ranks, OMP threads, runtime and total memory over all ranks, and environment variables.

- Resource: This is the definition of the resource that the campaign uses, defining total number of nodes accessible, cores per node, memory per node. We may want to define different queues here so that the manager can select based on the campaign's deadline and policy.

An example of a campaign definition can be:
```toml
[campaign]
deadline = "2d"

[campaign.ml-mapmaking]
context = "/scratch/gpfs/ACT/data/context-so-fixed/context.yaml"
area = "/scratch/gpfs/SIMONSOBS/so/science-readiness/footprint/v20250306/so_geometry_v20250306_lat_f090.fits"
output_dir = "/scratch/gpfs/SIMONSOBS/users/ip8725/git/so_mapmaking_campaign_manager/output"
bands = "f090"
wafer = "ws0"
comps = "TQU"
maxiter = 10
query = "obs_id='1575600533.1575611468.ar5_1'"
tiled = 1
site = "act"
[campaign.ml-mapmaking.resources]
ranks = 8
threads = 1
memory = "80000"  # in MBs
runtime = "80000" # in seconds
[campaign.ml-mapmaking.environment]
MOBY2_TOD_STAGING_PATH = "/tmp/"
DOT_MOBY2 = "/scratch/gpfs/SIMONSOBS/users/ip8725/act_test/act_dot_moby2"
SOTODLIB_SITECONFIG = "/scratch/gpfs/SIMONSOBS/users/ip8725/act_test/site.yaml"

[campaign.lat-null-test]
context="context.yaml"
area="somefile.fits"
output_dir="output"
maxiters=10
site="act"
query="timestamp_start > 2020-01-01T00:00:00Z && timestamp_end < 2020-01-09T23:59:59.999Z" # SQL-like query that sotodlib understands
[campaign.lat-null-test.mission]
chunk_duration="1d"
nsplits=8
```

The execution happens via 3 systems, the bookkeeper, the planner and the enactor:

- The bookkeeper knows the overall state of a campaign. It verifies if everything runs correctly, if the deadline is achievable and holds the general state of the campaign.

- The enactor is the system that executes the actual workflows on the targeted HPC. This is a pilot system currently, that allows us to acquire and run multiple executable concurrently on the overall resources. ( It is a single slurm job). It has the capability to run in resources already acquired or place a slurm job for the overall execution.

- The planner is trying to find an order of workflow execution that will minimize the total time of the campaign.

In addition to these I use a system called `slurmise` that records the runtime, memory and command of a workflow. This will allows to fit models and start having a runtime/memory prediction of standard workflows in the campaign. `slurmise` defines two types of important types: numerical and categories. Numerical values are by default the number of ranks and threads, while categorical can be the geometry of the run.
  - What do we do with the observations?
  - What are the categorical information for simulations?
  - If config files are used we can either use their md5 to keep them as categorical values, or create our own parser.

Further points of discussion:
- Do we need a web hosted API to submit campaigns?
- Do we need a way to define cadence of a campaign, how often it will run/ what will trigger it?
- Currently, it supports a single campaign. Should it support multiple campaigns that run at the same time?
- Will we have more complex workflows with dependencies between them that are not already defined in an `sotodlib` executable?
